spring:
  datasource:
    url: jdbc:mysql://localhost:3306/email_db?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
